databrickslabs/dbldatagen

- dbldatagen/data_generator.py
- dbldatagen/daterange.py
- dbldatagen/utils.py
- examples/example1.py
- examples/example4.py
- examples/example5.py
- examples/example6.py
- tutorial/2-Basics.py
> code cleanup

- CHANGELOG.md
- dbldatagen/_version.py
- docs/source/conf.py
- python/.bumpversion.cfg
- setup.py
Updated build version for new pre-release
> new release candidate

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
Added templates for new issues and pull requests. 
No code changes
> templates for filing issues and pull requests

- PULL_REQUEST_TEMPLATE.md
- README.md
- docs/source/extending_text_generation.rst
- tests/test_text_generation.py
Link pointed to old release of wheel - updated to point to latest release
> updated readme to point to latest wheel release

- dbldatagen/distributions/beta.py
- dbldatagen/distributions/data_distribution.py
- dbldatagen/distributions/exponential_distribution.py
- dbldatagen/distributions/gamma.py
- dbldatagen/schema_parser.py
- tests/test_distributions.py
- tests/test_schema_parser.py
Increase test coverage and minor fixes / enhancements
What types of changes does your code introduce to dbx?
Added additional coverage tests. Minor bug fixes / enhancements (new properties)
> additional coverage and minor fix

- docs/source/DATARANGES.md
What types of changes does your code introduce to dbx?
> fix for issue 86

- docs/source/options_and_features.rst
The word "unique" was mis typed as "unqique" in the docs.
What types of changes does your code introduce to dbx?
- [] Non code change (readme, images or other non-code assets)
did and what alternatives you considered, …
> Fix the typo at the word unique

- CONTRIBUTING.md
- dbldatagen/utils.py
- tests/test_utils.py
What types of changes does your code introduce to dbx?
minor fix
> fixed use of time strings to allow both seconds and  second etc

- .github/workflows/onrelease.yml
- .github/workflows/push.yml
> updates to build process

- CHANGELOG.md
- README.md
- dbldatagen/_version.py
- docs/source/conf.py
- python/.bumpversion.cfg
- setup.py
Updated version for release 3.1 - updates to version info
> Feature release v031

- CHANGELOG.md
- README.md
- dbldatagen/_version.py
- docs/source/conf.py
- python/.bumpversion.cfg
- setup.py
Updated labelling to comply with PEP440
> updated labelling to comply with PEP440

- dbldatagen/schema_parser.py
- tests/test_build_planning.py
- tests/test_schema_parser.py
Fix parsing and cleansing of quoted identifiers
> fixed handling of quoted identifiers

- README.md
Added note in Readme for support for specific modes of unity catalog enabled clusters
Changed badging to supply separate badge for downloads and link to PyPi package
Changes to Readme only
> Feature readme changes

- CHANGELOG.md
- dbldatagen/_version.py
- dbldatagen/data_generator.py
- dbldatagen/spark_singleton.py
- tests/test_logging.py
Fixed use of logger in _version and spark_singleton to use named logger
> fixed use of logger to get named logger

- README.md
Reformatting of readme example 
Readme formatting changes only
> minor readme reformatting

- CHANGELOG.md
- README.md
- dbldatagen/_version.py
- dbldatagen/column_generation_spec.py
- docs/source/conf.py
- python/.bumpversion.cfg
- setup.py
Changes for release - version update, bugfix to apply pandas optimizations to columns that have multiple features
> Release 033 post2

- CHANGELOG.md
- docs/source/extending_text_generation.rst
- docs/source/generating_cdc_data.rst
- docs/source/generating_json_data.rst
- docs/source/multi_table_data.rst
- docs/source/troubleshooting.rst
> Doc updates 032523

- CHANGELOG.md
- README.md
- dbldatagen/_version.py
- dbldatagen/data_analyzer.py
- dbldatagen/utils.py
- docs/source/conf.py
- docs/source/generating_json_data.rst
- python/.bumpversion.cfg
- setup.py
- tests/test_generation_from_data.py
Hotfixes for issues when using DataAnalyzer in Databricks Connect environment, or when the dataset contains a field
called summary
- [] Change to tutorials, tests or examples
Version has been revised
> Feature hotfixes

- CHANGELOG.md
PR to test updates to process - will be removed at end of testing
> PR To test updates to process

- CHANGELOG.md
Reverts databrickslabs/dbldatagen#278
> Revert "PR To test updates to process"

- CHANGELOG.md
- README.md
- dbldatagen/_version.py
- dbldatagen/data_generator.py
- docs/source/conf.py
- python/.bumpversion.cfg
- setup.py
- tests/test_serverless.py
Bumping version and updating changelog.
> Feature serverless support v2

- docs/source/using_standard_datasets.rst
> Fix typo in docs

- dbldatagen/spark_singleton.py
- dbldatagen/utils.py
- pyproject.toml
This is the initial PR to set up Ruff for linting and formatting. It enables the ANN rule set to enforce type hints.
> Fixing lints and warning from utils files

- dbldatagen/column_generation_spec.py
- dbldatagen/data_generator.py
- dbldatagen/datagen_constants.py
- pyproject.toml
- tests/test_serialization.py
Applies formatting and adds type hints to the `data_generator.py` module. I have also updated the docstrings and cleaned up several methods.
> Format `data_generator.py`

- dbldatagen/serialization.py
- pyproject.toml
Formatting and linting  `dbldatagen/serialization.py` module
> Linting serialization module
